### ISSUE TITLE
introduzir equivalência com açúcar sintático

### ISSUE THREAD

**Issue by arademaker** [arademaker/krr#17]
podemos introduzir e pré-processar `(equiv A B ...)`. Ou de forma mais simplificada, apenas o equiv binário.

**Comment by rkatz36368** [comment]
fiz um pull request referente a esse issue

**Comment by arademaker** [comment]
Feito, já aceitei o pull request. Commit 853f86b resolve problema e fiz alguns testes:

```
tableaux> (prove '(equiv (or A B) (or B A)))
nil
tableaux> (prove '(equiv (not (or A B)) (and (not B) (not A))))
nil
```
